//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcarusWikiExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IcarusWikiExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        internal static string error_unknown {
            get {
                return ResourceManager.GetString("error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICARUS Wiki Search.
        /// </summary>
        internal static string icarus_ext_display_name {
            get {
                return ResourceManager.GetString("icarus_ext_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Map via Icarus Intel.
        /// </summary>
        internal static string icarus_intel {
            get {
                return ResourceManager.GetString("icarus_intel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an interactive map in the browser (via icarusintel.com).
        /// </summary>
        internal static string icarus_intel_subtitle {
            get {
                return ResourceManager.GetString("icarus_intel_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICARUS Wiki Search.
        /// </summary>
        internal static string icarus_wiki_search {
            get {
                return ResourceManager.GetString("icarus_wiki_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the ICARUS wiki quickly..
        /// </summary>
        internal static string icarus_wiki_search_subtitle {
            get {
                return ResourceManager.GetString("icarus_wiki_search_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Map via Mapgenie.
        /// </summary>
        internal static string mapgenie {
            get {
                return ResourceManager.GetString("mapgenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an interactive map in the browser (via mapgenie.io).
        /// </summary>
        internal static string mapgenie_subtitle {
            get {
                return ResourceManager.GetString("mapgenie_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results :(.
        /// </summary>
        internal static string no_results {
            get {
                return ResourceManager.GetString("no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find any pages matching your query..
        /// </summary>
        internal static string no_results_subtitle {
            get {
                return ResourceManager.GetString("no_results_subtitle", resourceCulture);
            }
        }
    }
}
